# Generated by Django 2.2.4 on 2019-08-11 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_added_location_state_code_and_location_country_code_models'),
        ('common', '0002_added_location_state_code_and_location_country_code_models'),
        ('company', '0002_added_location_state_code_and_location_country_code_models'),
        ('job_listing', '0004_added_location_state_code_and_location_country_code_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='locationstatecode',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.LocationCountryCode'),
        ),
    ]
