# Generated by Django 2.2.4 on 2019-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_added_location_state_code_and_location_country_code_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationstatecode',
            name='type',
            field=models.TextField(default='State', max_length=255),
            preserve_default=False,
        ),
    ]
