# Generated by Django 2.2.4 on 2019-08-17 07:44

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0004_added_location_state_code_and_location_country_code_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='publish_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='status',
            field=django_fsm.FSMIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
