# Generated by Django 2.2.4 on 2019-08-17 02:18

import apps.job_listing.enums
from django.db import migrations, models
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0004_added_location_state_code_and_location_country_code_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='publish_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='status',
            field=enumchoicefield.fields.EnumChoiceField(default=apps.job_listing.enums.JobListingStatus(1), enum_class=apps.job_listing.enums.JobListingStatus, max_length=9),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
