# Generated by Django 2.2.4 on 2019-08-18 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0004_added_location_state_code_and_location_country_code_models'),
        ('job_listing', '0007_move_job_listing_response_models_to_job_listing_response_app'),
        ('common', '0004_added_type_property_to_location_state_code_model'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='JobListingResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applicant.Applicant')),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_listing.JobListing')),
            ],
            options={
                'db_table': 'job_listing_response_joblistingresponse'
            }
        ),
        migrations.CreateModel(
            name='JobListingResponseOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.TextField(max_length=100)),
                ('outcome_comments', models.TextField()),
                ('outcome_date', models.DateTimeField(auto_now_add=True)),
                ('job_listing_response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_listing_response.JobListingResponse')),
            ],
            options={
                'db_table': 'job_listing_response_joblistingresponseoutcome'
            }
        ),
        migrations.CreateModel(
            name='JobListingResponseDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('file_size', models.IntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.File')),
                ('job_listing_response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_listing_response.JobListingResponse')),
            ],
            options={
                'db_table': 'job_listing_response_joblistingresponsedocument'
            }
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
