# Generated by Django 2.2.5 on 2019-09-07 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing_response', '0001_add_job_listing_response_models_migrated_from_job_listing_app'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='joblistingresponse',
            table=None,
        ),
        migrations.AlterModelTable(
            name='joblistingresponsedocument',
            table=None,
        ),
        migrations.AlterModelTable(
            name='joblistingresponseoutcome',
            table=None,
        ),
    ]
