# Generated by Django 2.2.4 on 2019-08-09 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('website_url', models.TextField(null=True)),
                ('github_url', models.TextField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.IntegerField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applicant.Applicant')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ProgrammingLanguage')),
            ],
        ),
    ]
