# Generated by Django 2.2.4 on 2019-08-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_add_many_to_many_relationship_fields_to_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='location',
        ),
        migrations.AddField(
            model_name='applicant',
            name='city',
            field=models.TextField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
