# Generated by Django 2.2.4 on 2019-08-11 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_added_location_state_code_and_location_country_code_models'),
        ('applicant', '0003_added_location_state_code_and_location_country_code_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='common.LocationCountryCode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='post_code',
            field=models.TextField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='common.LocationStateCode'),
            preserve_default=False,
        ),
    ]
