# Generated by Django 2.2.4 on 2019-08-09 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('applicant', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(max_length=255)),
                ('description', models.TextField()),
                ('position_type', models.TextField(max_length=100)),
                ('contract_length', models.IntegerField(null=True)),
                ('salary', models.IntegerField(null=True)),
                ('salary_frequency', models.TextField(max_length=100, null=True)),
                ('expiry_date', models.DateTimeField(default=None, null=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Location')),
            ],
        ),
        migrations.CreateModel(
            name='JobListingResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applicant.Applicant')),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_listing.JobListing')),
            ],
        ),
        migrations.CreateModel(
            name='JobListingTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_listing.JobListing')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='JobListingResponseOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.TextField(max_length=100)),
                ('outcome_comments', models.TextField()),
                ('outcome_date', models.DateTimeField(auto_now_add=True)),
                ('job_listing_response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_listing.JobListingResponse')),
            ],
        ),
        migrations.CreateModel(
            name='JobListingResponseDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('file_size', models.IntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.File')),
                ('job_listing_response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_listing.JobListingResponse')),
            ],
        ),
        migrations.CreateModel(
            name='JobListingRequiredDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_listing.JobListing')),
            ],
        ),
        migrations.CreateModel(
            name='JobListingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_listing.JobListing')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ProgrammingLanguage')),
            ],
        ),
    ]
