# Generated by Django 2.2.4 on 2019-08-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('job_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='languages',
            field=models.ManyToManyField(through='job_listing.JobListingLanguage', to='common.ProgrammingLanguage'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='tags',
            field=models.ManyToManyField(through='job_listing.JobListingTag', to='common.Tag'),
        ),
    ]
