# Generated by Django 2.2.4 on 2019-08-09 08:52

from django.db import migrations
import enumchoicefield.fields
import job_listing.enums


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing', '0002_add_many_to_many_relationship_fields_to_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='position_type',
            field=enumchoicefield.fields.EnumChoiceField(default=job_listing.enums.JobPositionType(4), enum_class=job_listing.enums.JobPositionType, max_length=8),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary_frequency',
            field=enumchoicefield.fields.EnumChoiceField(default=job_listing.enums.SalaryFrequency(6), enum_class=job_listing.enums.SalaryFrequency, max_length=12),
        ),
    ]
